# https://webui.me
# https://github.com/webui-dev/webui
# Copyright (c) 2020-2025 Hassan Draga.
# Licensed under MIT License.
# All rights reserved.
# Canada.

name: Linux-Arch
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Arch Linux Docker Image
        run: |
          docker build -t archlinux:latest - <<EOF
          FROM archlinux:latest
          RUN pacman -Syu --noconfirm git npm make gcc clang llvm lld
          EOF

      - name: Run build inside Arch Linux container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            archlinux:latest \
            bash -c "
              npm i -g esbuild &&
              chmod +x bridge/build.sh &&
              ./bridge/build.sh &&
              make debug &&
              make &&
              make WEBUI_USE_TLS=1 debug &&
              make WEBUI_USE_TLS=1
            "
